### ISSUE TITLE
related_entries not working

### ISSUE THREAD

**Issue by johandouma** [rsanchez/dynamo#1]
Hi rsanchez,

Seriously great add on!

related_entries don't seem to work within the {exp:dynamo:entries}, is that by design? I'd love to see that working, if it's something that's not too much trouble. 

Thanks, 
Johan

**Comment by rsanchez** [comment]
It's not by design. The truth is, I never tested with reverse_related_entries and related_entries. Dynamo is just an extension of channel:entries, so I assumed it would work, but apparently not. I'm not sure when I'll have time to troubleshoot this, so I'll leave it as an open issue.

**Comment by rsanchez** [comment]
What exactly is the issue? Does {related_entries} render blank? Or not render at all?

**Comment by johandouma** [comment]
They're not parsed at all, they're displayed in the final HTML as {related_entries id="suburb"}<p>Area: <strong>{title}</strong>, ... </p>{/related_entries}

**Comment by rsanchez** [comment]
Just confirmed this is not working.

**Comment by rsanchez** [comment]
I added a fix in the develop branch, can you download/install and test? https://github.com/rsanchez/dynamo/zipball/develop

**Comment by johandouma** [comment]
Yes it works. Anywhere I can make a donation? What's you paypal address?
