### ISSUE TITLE
Does no_results works?

### ISSUE THREAD

**Issue by davorpeic** [rsanchez/dynamo#12]
Hi, I can't get {if no_results} to work if {exp:dynamo:entries} has no entries to show. I also tried using {count} to display some text, but don't happens anything. Is there a workournd?

thanx

**Comment by rsanchez** [comment]
Short answer, yes it works. I've used it myself! :)

Do you have your dynamo:entries tag nested inside some other tag? It could be that you're having a no_results conflict.

**Comment by davorpeic** [comment]
Your post was really helpful Rob :)

I have it inside the Switchee, so {if switchee_no_results} fixed the problem :)

Thank you
