### ISSUE TITLE
Question on single entries

### ISSUE THREAD

**Issue by ghost** [rsanchez/dynamo#13]
Hi,
I have the following 

site.com/products <= here is where my dynamo filter is and returns the results.
site.com/products/single_entry <= here is where i can view a single entry returned from the results.

But now I would like to add "previews - next" pagination on the single entry but based on the filtered results that were done in site.com/products

Is this possible?

perhaps by storing the search_id or something?

**Comment by rsanchez** [comment]
You'd have to store the search_id somehow. Maybe in a cookie using PHP or one of the cookie plugins on devotee. Or you could store it in a url segment somehow. It's probably not going to be easy to do so. It's a nice feature request, though.
