### ISSUE TITLE
Set form's return parameter to current page

### ISSUE THREAD

**Issue by katrinkerber** [rsanchez/dynamo#14]
The form's return parameter currently looks for a specific template. I only want an index.html file within a template group and then use main category links which are accessible in the site's navigation and add segments to the URL. I am using "Low Seg2Cat" to listen for the selected main category in the URL.

For example, a user might go to www.shop.com/jewelry/earrings/, where 'jewelry' is the template group and 'earrings' is the category_url.

I can get dynamo to filter by other children categories by using a sub-template, i.e 'jewelry/filter/', but that means I am loosing the ability to keep the 'earrings' category in place/selected as well.

Is there a way to set the return parameter to just return to the current page, without it looking for a matching sub-template? 

For example: return="{homepage}/{segment_1}/{segment_2}/"

When I am trying this, I get the error that the template does not exist.

**Comment by rsanchez** [comment]
I'll have some time this weekend to take a look at this and your other issue.

**Comment by katrinkerber** [comment]
That would be fantastic, thanks Rob.

**Comment by rsanchez** [comment]
Are you using Freebie or Structure? What's the exact error that it prints out? You should be able to omit the return parameter altogether if you want it to redirect to the current url.

**Comment by katrinkerber** [comment]
Mmmm, for some reason what I tried before ({homepage}/{segment_1}/{segment_2}/) works just fine now. Sorry about that.

Is there a variable to call the value of the search id - something like {search_id}?

I'd like to achieve something like this if possible:

```
{if segment_2 != search_id}
    search_id="{segment_3}"
{/if}
{if segment_2 == search_id}
    search_id="{segment_2}"
{/if}
```

**Comment by rsanchez** [comment]
There's no conditional like that, but I think you can achieve what you're going for using search_id="{last_segment}"

**Comment by katrinkerber** [comment]
Great idea, but I am using pagination as well, so unfortunately that breaks it :(

If there isn't another way, then my Plan B is to make sure there is always a second segment by adding 'all' to the page where is displays all products.

Thank you very much for your help and great add-on.
