### ISSUE TITLE
This is a non-secure form. This form will be sent in a way that is not secure. Are you sure you want to send it?

### ISSUE THREAD

**Issue by vladilin** [rsanchez/dynamo#16]
Hi Guys Getting this error. 
 This is a non-secure form. This form will be sent in a way that is not secure. Are you sure you want to send it?

 I am using return="/{segment_1}"

Any ideas?

Thank you in advance

**Comment by rsanchez** [comment]
It uses your site_url to generate the form action. I'd recommend changing your site URL to use https.

**Comment by vladilin** [comment]
Hi Allan, Actually I don't want the whole site to have HTTPS, 

I am using .htacess to redirect the store section to https

Is there any way to hack it?

Thank you :D

**Comment by rsanchez** [comment]
Just pushed a hotfix, adds the secure_action and secure_return parameters. Just set them to yes and you should be good.

**Comment by vladilin** [comment]
You are an awesome super programmer god!
