### ISSUE TITLE
Error  The following tag cannot be processed:  {exp:dynamo:selected}

### ISSUE THREAD

**Issue by vladilin** [rsanchez/dynamo#18]
Hello, getting this error:

Error

The following tag cannot be processed:

{exp:dynamo:selected}

Please check that the ‘dynamo’ module is installed and that ‘selected’ is an available method of the module

My code is pretty simple here:

{exp:dynamo:form parse="inward" return="/home_save/collection" search_id="{segment_3}" name="test" dynamic_parameters="category" separator:category="&"}

```
                              {exp:channel:categories category_group="6" style="linear"}
                    <p><input name="category[level]" type="radio" value="{category_id}" {if {exp:dynamo:selected value="{category_id}" in="{category}"}}checked="checked"{/if} /> {category_name}</p>
                  {/exp:channel:categories}

                              </div>



        <select name="limit">
                <option value="">Result Limit:</option>
            <option value="1"{if limit == 1} selected="selected"{/if}>1</option>

            </select>

        <select name="orderby">
                <option value="date">Sort By:</option>
                <option value="date"{if orderby == "date"} selected="selected"{/if}>Date</option>
                <option value="title"{if orderby == "title"} selected="selected"{/if}>Title</option>
            </select>

        <select name="sort">
                <option value="asc">Order In:</option>
                <option value="asc"{if sort == "asc"} selected="selected"{/if}>Ascending</option>
                <option value="desc"{if sort == "desc"} selected="selected"{/if}>Descending</option>
            </select>
       <input type="submit" class="Osearch" value="Search" />
```

{/exp:dynamo:form} 

What am I doing wrong?

**Comment by rsanchez** [comment]
Which branch are you using, master or develop?

**Comment by vladilin** [comment]
I tried both. :/

**Comment by rsanchez** [comment]
Well, it's only in the develop branch, there's no reason I know of that you'd get that error using develop. Try re-installing the develop branch is all I can advise. I can see that the selected method is indeed in the mod.dynamo.php file.

**Comment by vladilin** [comment]
You were right not sure why it did not work the 1st time, sorry to bother you. Although, why are there 2 branches when there develop one is the one that has all the cool functions?

Do you have a donate box? IOU coffe

**Comment by vladilin** [comment]
I think I know how he reached this error:
https://devot-ee.com/add-ons/dynamo
From Devotee page both links lead to Master, you have to manually go into Github and change Branch to Development Branch
