### ISSUE TITLE
Structure URLs and Dynamo segment issue

### ISSUE THREAD

**Issue by snorith** [rsanchez/dynamo#19]
Thanks for the great extension, I'm glad that it solves the dynamic parameters issue with pagination.

I'm having a problem with the URL constructed by Dynamo though, the extra segment it adds is confusing Structure and I'm not sure where to look for a solution. My URLs look like this:

/basepage/childpage

with a dynamo form submitting to that page I get a submitted URL of:

/basepage/childpage/1cec15b51185cdcbfd24ed1313df8adc

but the resulting template for that URL is what is assigned for /basepage, though Structure wants to pull the channel content for 'childpage' into it. So part of Structure knows it's on 'childpage' while part of it wants to use the template for the 'basepage'.

Any ideas on how to start debugging this segment issue?

thx!

**Comment by rsanchez** [comment]
Yeah, you need to use something like [Template Routes](https://github.com/rsanchez/template_routes), [Freebie](https://github.com/averyvery/Freebie), or Zoo Triggers. Structure only matches EXACT URLs, so if you have extra segments, you need one of these other addons.
