### ISSUE TITLE
Deprecated function

### ISSUE THREAD

**Issue by ronaldpoi** [rsanchez/dynamo#23]
I get this message:

Deprecated function assign_relationship_data() called in system/expressionengine/third_party/dynamo/mod.dynamo.php on line 194.
From template tag exp:dynamo:entries in articulosypublicaciones/lista.
Deprecated since 2.6.

Is this important / serious?

**Comment by rsanchez** [comment]
Deprecated warnings are harmless, so you don't need to worry about it. I'll fix it at some point, but not today.

**Comment by rsanchez** [comment]
Just pushed a new version to fix this.
