### ISSUE TITLE
1054

### ISSUE THREAD

**Issue by ikaikahussey** [rsanchez/dynamo#24]
Hi,

I'm getting this error:

Error Number: 1054

Unknown column 'addon_module' in 'where clause'

SELECT \* FROM (`exp_developer_log`) WHERE `function` = 'assign_relationship_data()' AND `line` = 194 AND `file` = 'system/expressionengine/third_party/dynamo/mod.dynamo.php' AND `deprecated_since` = '2.6' AND `use_instead` IS NULL AND `addon_module` = 'Dynamo' AND `addon_method` = 'entries' AND `template_id` = '827' AND `template_group` = 'internal' AND `template_name` = 'index' ORDER BY `log_id` desc

Filename: libraries/Logger.php

Line Number: 116

**Comment by ikaikahussey** [comment]
Just wanted to let you know that I commented out line 194, and it seems to be working ok.

**Comment by rsanchez** [comment]
Just pushed a new version to fix this.
