### ISSUE TITLE
Plugin throwing Deprecated Function errors in Developer Log

### ISSUE THREAD

**Issue by MLohrman** [rsanchez/dynamo#26]
Plugin still works, just thought I would let you know. Thanks
![screen shot 2013-08-15 at 4 31 34 pm](https://f.cloud.github.com/assets/1496829/972270/afa6028e-05f7-11e3-9fca-54d70ec0d473.png)

**Comment by rsanchez** [comment]
Thanks! I actually pushed up a new version yesterday to address this. Have you grabbed the latest?

**Comment by MLohrman** [comment]
didn't even notice, thanks!
