### ISSUE TITLE
Link to Filtered Results

### ISSUE THREAD

**Issue by andrewlphilpott** [rsanchez/dynamo#29]
Is there any way to link to a filtered page? For example, I've got some links on my homepage that are callouts to specific categories. Is there a way to convert those category links to work with the filter?

**Comment by rsanchez** [comment]
If you are on EE 2.7.2, you can do this natively with dynamic_parameters and query strings. site.com/foo/bar?category=7

**Comment by andrewlphilpott** [comment]
Yeah, I was thinking about maybe doing that. Just wondering if there was a way to do it without rebuilding this really big filter form that I'm looking at.

**Comment by rsanchez** [comment]
I think you can do it without rebuilding. Should just work with dynamo automatically, since it extends channel:entries.

**Comment by andrewlphilpott** [comment]
Oh yep, you're right.

On a probably unrelated note, I've noticed that an existing dynamo form is causing the following error in IE:

The action you have requested is invalid.

Any idea off the top of your head what the issue might be? If not, I can just convert the form to a vanilla form and use GET variables.

**Comment by rsanchez** [comment]
I'm sure it's something Secure Forms related. You might have to turn that setting off globally. Not sure why it would only break on IE, this is probably something in the EE core, maybe the EE_Security.php class. You can also turn off secure forms for individual module actions by adding a 1 to the csrf_exempt column in the exp_actions table for Dynamo actions.

**Comment by andrewlphilpott** [comment]
Cool. Thanks for your help!

**Comment by johnj24** [comment]
Rob, is there any reason not to link to the hash id? Does the hash id expire at some point? I understand the ?category=1 option, but that doesn't allow for pagination as far as I can tell.

**Comment by rsanchez** [comment]
The hash does indeed expire after a while.

You can make the ?category=1 option work with pagination with this simple trick. This is all native in a plain old {exp:channel:entries dynamic_parameters="category"} (assuming you are on a recent version of EE), no addons necessary.

```
{paginate}
  {pagination_links}
    <ul>
      {first_page}
        <li><a href="{pagination_url}{if current_query_string}?{current_query_string}{/if}" class="page-first">First Page</a></li>
      {/first_page}

      {previous_page}
        <li><a href="{pagination_url}{if current_query_string}?{current_query_string}{/if}" class="page-previous">Previous Page</a></li>
      {/previous_page}

      {page}
        <li><a href="{pagination_url}{if current_query_string}?{current_query_string}{/if}" class="page-{pagination_page_number} {if current_page}active{/if}">{pagination_page_number}</a></li>
      {/page}

      {next_page}
        <li><a href="{pagination_url}{if current_query_string}?{current_query_string}{/if}" class="page-next">Next Page</a></li>
      {/next_page}

      {last_page}
        <li><a href="{pagination_url}{if current_query_string}?{current_query_string}{/if}" class="page-last">Last Page</a></li>
      {/last_page}
    </ul>
  {/pagination_links}
{/paginate}
```

**Comment by johnj24** [comment]
Genius.  I was not aware of the {current_query_string} tag. Thanks Rob!
