### ISSUE TITLE
Please don't close Dynamo down

### ISSUE THREAD

**Issue by vladilin** [rsanchez/dynamo#34]
Yes EE has improved their search results, BUT as far as I know you cannot show the selected parameters. IE
[if orderby == date] selected="selected"[if]
OR 
Sort search results via dynamic variables, or resort the results. This thing is so awesome.

Hell you can't even search without submitting a key word, you need  2 separate forms on the page... the search form and the dynamic sorting form.

**Comment by rsanchez** [comment]
Don't worry, I won't ever delete it. And I'm pretty sure the current version still works with the latest EE. I just won't be making any feature additions / updates for the foreseeable future.
