### ISSUE TITLE
Fatal error: Call to undefined method Localize::decode_date()

### ISSUE THREAD

**Issue by vladilin** [rsanchez/dynamo#36]
Is there a way to make a date range. 

I imagine I can use name="search:entry_date" to find all entries in a single day, but is there any way to set:

find entries from entry_date to entry_date?

Thanks in advance.

**Comment by rsanchez** [comment]
EE has native parameters for this: [`start_on`](https://ellislab.com/expressionengine/user-guide/channel/channel_entries.html#start-on) and [`stop_before`](https://ellislab.com/expressionengine/user-guide/channel/channel_entries.html#stop-before).

**Comment by vladilin** [comment]
Ah yes that makes sense. I didn't think if them as dynamic parameters.  Thank you

Vlad

<div>-------- Original message --------</div><div>From: Rob Sanchez notifications@github.com </div><div>Date:11/04/2015  22:06  (GMT+07:00) </div><div>To: rsanchez/dynamo dynamo@noreply.github.com </div><div>Cc: vladilin vlad.ilin@gmail.com </div><div>Subject: Re: [dynamo] More of a inquiry than an issue. (#36) </div><div>
</div>EE has native parameters for this: start_on and stop_before.

**Comment by vladilin** [comment]
Hey Rob,

I tried this one, but get this error
Fatal error: Call to undefined method Localize::decode_date() in /expressionengine/third_party/dynamo/mod.dynamo.php on line 157

Any advice?

**Comment by vladilin** [comment]
I fixed this by changing decode_date to format_date. Even though I read somewhere that “format” is “deprecated” and we should be using “decode_date” instead apparently that is not the case because when I changed that in my template it worked and I stopped getting that error.
