### ISSUE TITLE
Using selected:category

### ISSUE THREAD

**Issue by jamestflynn** [rsanchez/dynamo#5]
Hello Rob,

I have the static check in place to test and this is working properly:

{if {selected:category="510"}}{/if}

But when I try to use with the following:

{if {selected:category="{cat_id}"}}{/if}

I get a error stating the below. Can I easily use this same selected check and pass in the cat_id on the fly?

Parse error: syntax error, unexpected '{'

Great plugin btw, will do exactly what I need to enable category "filtering" on the cartthrob site I am working on.

Thanks,
James

Thanks,
James

**Comment by rsanchez** [comment]
It's definitely a parse order issue. Where's the {cat_id} coming from?

**Comment by jamestflynn** [comment]
Thanks for the reply Rob, the order is currently:
- dynamo:form
  - exp:gwcode_categories (to run through the categories and {cat_id} tag comes from this)
    - input type="checkbox" name="category[]" value="{cat_id}" {if {selected:category="{cat_id}"}}{/if}

**Comment by jamestflynn** [comment]
I just dropped in a simple jquery function that will auto check those to resolve:

(function() {
<?php
    $allSelected  = "{category}";
    $allSelectedArray = explode("&", $allSelected);
    foreach ($allSelectedArray as $value) { 
       echo "$('#".$value."').prop('checked', true);";
    }
?> 
});
