### ISSUE TITLE
Getting PHP error on v1.0.3

### ISSUE THREAD

**Issue by dehuszar** [rsanchez/dynamo#8]
Hi Rob,

I tried to use version 1.0.3, primarily to take advantage of keyword searching (I can't seem to make it go and there's no examples in the docs), but have been getting the following error:

``` php
Fatal error: Call to undefined function ascii_to_entities() in /home/sam_allen/ccr.no1cooperative.com/system/expressionengine/third_party/dynamo/mod.dynamo.php on line 288
```

Any ideas?

**Comment by rsanchez** [comment]
Whoops. Version bump to 1.0.4 with a fix.
