### ISSUE TITLE
matrix fields

### ISSUE THREAD

**Issue by ghost** [rsanchez/dynamo#9]
hi,
i'm having problems with matrix fields inside of dynamo i'm not sure where the problem could be 

i can grab dynamic parameters of a ff matrix field without a problem 
but anything like this simply doesn't work:

{matrix_field search:matrix_cel_color="=RED"}{title} {/matrix_field}

If i put this inside of exp:channel:entries then it works fine but not inside of dynamo

**Comment by rsanchez** [comment]
Is this in a dynamo:entries tag pair? does the matrix tag pair work without the search:matrix_cell_color param?

**Comment by ghost** [comment]
yes it's inside the dynamo:entries tag pair
it's odd because my checkboxes work perfectly with the search:matrix param

```
    <label><input type="checkbox" name="search:matrix_field" class="filter-input" value="matrix_cell_result">Option 01</label>
```

**Comment by rsanchez** [comment]
Why don't you post the entirety of your template so I could take a closer look?

**Comment by ghost** [comment]
Sure

```
{exp:dynamo:form return="products/test"}
<fieldset class="checkboxes">     
    <div class="clearfix">
    <div class="inline half">   
    style: <br>
    <label><input type="checkbox" name="search:style" class="filter-input" value="modern">modern</label>
    <label><input type="checkbox" name="search:style" class="filter-input" value="contemporary">contemporary</label>
    <input type="submit">
    </div>          
</div>
{/exp:dynamo:form}
```

i tried the {if marrix_field == value} ... {/if} doesn't work either 

Thanks :)

**Comment by ghost** [comment]
Another template: 

{exp:channel:entries channel="meubelen" limit="1"}
{stijl_nl search:stijl_nl_col="MODERN"} HUISSTIJL {/stijl_nl}
{/exp:channel:entries}

this works perfect
if i do this:

{exp:dynamo:form return="meubels/slaapkamer" limit="1"}
{stijl_nl search:stijl_nl_col="MODERN"  limit="1"} HUISSTIJL {/stijl_nl}
{/exp:dynamo:form}

It won't work anymore.

**Comment by rsanchez** [comment]
I see now, channel:entries field parsing is not available in the dynamo:form tag, only in the dynamo:entries tag. What you did was a good solution.

**Comment by ghost** [comment]
I'm wondering if the option will be available in the future
as of now it is a bit messy there are more than 10 templates to only serve this purpose. (and more to come)

thanks :)
